### ISSUE TITLE
关于一些改进组件的问题

### ISSUE THREAD

**Issue by yige-yigeren** [Baka632/aneot-vintage#26]
你可以删除forceflash的组件和相关的页面引用，这个功能是为了刷新缓存尽快获取更新而设计的。
/forceflash.html
仅在/forceflash.html和主页有使用

**Comment by Baka632** [comment]
嗯...我知道这个forceflash对这个项目是不需要的。
但是我倾向于在 原仓库有更新的时候直接把原仓库的 Markdown 文件无脑甩进本项目的 wwwroot 文件夹中，如果直接删除，下一次原仓库更新时我就要重新再删一遍（悲）

**Comment by yige-yigeren** [comment]
> 嗯...我知道这个forceflash对这个项目是不需要的。 但是我倾向于在原仓库有更新的时候直接把原仓库的 Markdown 文件无脑甩进本项目的 wwwroot 文件夹中，如果直接删除，下一次原仓库更新时我就要重新再删一遍（悲）

一个比较简单的步骤是在github action中配置删除，这样配置好一次就行

**Comment by Baka632** [comment]
删除 forceflash.md 页的同时，也要在主页面和期刊列表页中删除对 forceflash 的引用，用 GitHub Action 的话应该不大方便...

先搁置这个问题，等 #23 完成后，我再继续寻找这个问题的解决方案罢（

**Comment by Baka632** [comment]
通过新增的```AnEoT.Vintage.Tool```项目，此问题已解决！（顺带还删除了installpwa组件www）

你还有什么建议吗？如果没有的话我就关 Issue 了~

**Comment by yige-yigeren** [comment]
没啥了，installpwa页面也可删了

**Comment by yige-yigeren** [comment]
最近关于pwa组件应该还有一些少量的配置更新

**Comment by Baka632** [comment]
> 没啥了，installpwa页面也可删了

其实已经删除了（乐）

那我就关 Issue 了
